version: '3.8'

services:
  postgres:
    image: postgres:15.3
    container_name: egov-postgres
    environment:
      POSTGRES_USER: "egov"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "egov"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:


networks:
  app-network:
    driver: bridge
